services:
  node:
    build:
      context: ./node
    container_name: ${COMPOSE_PROJECT_NAME}-node
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=3000
    networks:
      - customer_net
      - traefik_proxy
    # Traefik labels provided via prod/dev override files

networks:
  customer_net:
    driver: bridge
  traefik_proxy:
    external: true
